# Example configuration file
#
# To use, copy this template and name it `config.yml`
# cp config.example.yml config.yml

telegram:
  token: YOUR_BOT_TOKEN
  chat_id: YOUR_CHAT_ID

thresholds:
  - value: 60 # 60°C
    duration: 600 # Must exceed 60°C for at least 600 seconds before alerting
  - value: 70
    duration: 300 # 5 minutes
  - value: 80
    duration: 120 # 2 minutes